{% set version = '1.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-parmigene
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/parmigene_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/parmigene/parmigene_{{ version }}.tar.gz
  sha256: 44db54941dc81c8b145a857df961e3901f518853e7050da4d42ef8ef71c7f918

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('parmigene')"           # [not win]
    - "\"%R%\" -e \"library('parmigene')\""  # [win]

about:
  home: https://github.com/sales-lab/parmigene
  license: AGPL-3.0-only
  summary: Parallel estimation of the mutual information based on entropy estimates from k-nearest
    neighbors distances and algorithms for the reconstruction of gene regulatory networks
    (Sales et al, 2011 <doi:10.1093/bioinformatics/btr274>).
  license_family: AGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ArneKr
    - FrodePedersen
    - MathiasHaudgaard

# Package: parmigene
# Version: 1.1.0
# Date: 2020-07-28
# Title: Parallel Mutual Information Estimation for Gene Network Reconstruction
# Author: Gabriele Sales <gabriele.sales@unipd.it>, Chiara Romualdi <chiara.romualdi@unipd.it>
# Maintainer: Gabriele Sales <gabriele.sales@unipd.it>
# Description: Parallel estimation of the mutual information based on entropy estimates from k-nearest neighbors distances and algorithms for the reconstruction of gene regulatory networks (Sales et al, 2011 <doi:10.1093/bioinformatics/btr274>).
# License: AGPL-3
# URL: https://github.com/sales-lab/parmigene
# BugReports: https://github.com/sales-lab/parmigene/issues
# NeedsCompilation: yes
# Packaged: 2020-08-03 08:54:00 UTC; border
# Repository: CRAN
# Date/Publication: 2020-08-03 09:50:03 UTC
