appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: jjtN/8XvyWqdY9BNivHmgjXb2ej6xtb7r3NLlL2/EF1nBhFbY8fd+2XpPv5g4igJatoBaomBjP8QZVcU/QeS+aVgcpwAREGybjIwfZpC7tG4+sDfK8hW6TUdkt6fy4viIkhv8DkGyjnAlqroJ7hAbgBySMDWHa8WSDX2Q4Mr2jF5HxzNf70PNxtiYATcbT6uD5qHKzVxpYWvhEGNvdWCSezLqEtNjteMGvlNTC5mS1eYQdb+uNBen2o3wOqPxoKjZ0lJjNQOq00DSKT6PlZgzlji803q1h0X692Z9/qKbEGYRHlPeMl9NZ9LVWsWpamZHme1GRNuzfCaIYmZDr6IdK5Pi5gDeVAEPjACxA0gpA0Xu7/CzMiKG9eOG06fUojZrCyRMcstry2MMWszY+ER1eQTMbHqsJrnPamHDQG6xIiFNN7Y90xWXI3IskByo8n7z/+46ojg1ivirTQbED2H6AvHHcDIZVkkc9SXBgtUuVHQ9slndtV+SbM/f71PFrIxTfNZk8oYhG4JzWsOLw0rpLhj/BTDlnwPd4hvD5NDdZn5GWS/eI0qtu9Qk6kTqHFjJmaS1BiKfYEmk+RzqHHPo5pWa/9hz9y6v036JRe4U+Z3Ras6gdE2Ekn9wPsXhw1rkyY5Ls4VOT6zLJW8AKgXT6Rv86+/DyFUFbpukCDf8Ew=}
