travis:
  secure:
    BINSTAR_TOKEN: MALm0UMNyY6jklUOpEr41FesXh29yw35USb+wBnb58hAAOKZVulLi+9jKXEtxmA2/Y6bmFoxYUGf1DAkM34aZqvJ7OYgn0aTpwWE0Be4CnBNV4w6wlbQKBdP6qx8PoyH02W+E+FSAKS3aW4DcnjybHZgHNdRHHhW7v+Hq+gs/gXdEqkUXjEl8VdtYhAhDbPcHXSERhCCIxeegH2bwhnJ8dTEMLsWY6R2vVUeSrETd95eWzzX2tcxPC7+45h2rQAWTj48ph5xu4U/mSK/maaVy+Dr0RBuXGZrSydSX6fp9f2Kuf+RPqzi3oZD6bbMR9+MeiYWU1T/02L88v7jxG+njWzEeoo4+3/q24Czf7sZ5Gq6DMGeUf87UKQuwbUpSBsv/DZ7wCA+/iKeC4XCN4JFe94YiVmzd9lVRHAefbLuYV0c+3X7Hk9MBz5d2Q5A5hj9V+QK8/90Ot3pLPClp/WYmIZe0FNzP6eEfuOsX9eX/CPHbsxo3YIKDa3buHfJR0rjW7wemzYJ3jF0lNuM+b5T9AU7yCmatxoKboru4qRkNrr86BQ95V1CHbE1VIgeLKUDCeL/bQDjw8GgjyeiMDRwzXk5sHzS4eqEXyU7Rgq/tsfIJ3iCYhpvBujFMNfO91/1AEQs6HLHO5MPparSRps4sH/upaa+uYfSbJOIlr17CZw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
