travis:
  secure:
    BINSTAR_TOKEN: ZgMN4m73KdH5FFFPgz7UENvwUuzh27Ly9T29a1NVsQjTRptDFJksbHqGZyrbNwv6tULikp9qbnqXp6P7e/3ii9yQBAw9PjzYOWz41tDhNsVSLjn+X5XetGNY2tzgEjUBodbbEzorQtrZTWiEtpKn07MjVd2Rp5Pla8ex3yPB0NYGZfAkMhhj0fsiIDGi4EJsBqAfN3vKBlJqH12ugkZ0lAGy2jTCAz0MeC4ObPzNyNLI/j02AScUyVgIzJBVe6HW0afNeWGL7rzNKaLvcSmV05AbFiC0PCrCOKvDs+gLVIXUUsoWg9suzBw7LvkzIXy+ExdeZEEHzwgwQ228FkqDLDP1yZ1X37Ywp/4Io4EKkBIdF0qJtOlw3TMPPWLTCt6BIn9zG3lkU2My4/VIgmS/QXCbsPc56+XqrIgzAe29PJVX8hyHs5HkTXNN6sJ1+NbjzUulGzFuyw7e939LJcFnRSL8pqkN6+D9GEIqjjro21VZNdx5iK6Q/dvDyya0jMgdpm1uIVALocprUK8bmlcgHJWLXKYyr56POn0GV8gF1YrH1aSE/JQ8Had0w2Gkjv7FlkS6FVj0eMYIoNfu4XT3cr+dXKm3zZK2MaUgH7ldsTMd/GTnHpmTNs3tkzEk/CYxdlAWgzYg+c93TdROLxIymiDqwIy8ki8EcwyQWbkX25Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
